
# DB Config file
clientconfig:
    # type can be http or file,if use file,read config local
    type: http
    url: http://172.16.0.143:8881/systemconfig/endpoint
    readlocal:
      - xx_tenant
      - xx_metadata

# Avoid using the default 8080 port for RESTFul services
server:
   applicationConnectors:
     - type: http
       port: 8081
   adminConnectors:
     - type: http
       port: 8082

# Logging For the record
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO,
  # DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console
      timeZone: GMT+08:00
    - type: file
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: logfile.log
      archivedLogFilenamePattern: logfile-%d.log.gz
      archivedFileCount: 5
      timeZone: GMT+08:00
    - type: gelf
      host: udp:172.16.0.143
      extractStackTrace: true
      filterStackTrace: true
      includeFullMDC: true
      additionalFields:
         data_center: DC01
         rack: R5C2
         inception_year: 2016
      additionalFieldTypes:
         inception_year: long
         request_id: long
