
# DB Config file
clientconfig:
   # type can be http or file,if use file,read config local
   type: file
   url: http://172.16.0.143:8881/systemconfig/endpoint
   readlocal:
      - xx_tenant
      - xx_metadata

redis:
  # The redis server's address; required.
  endpoint: 172.16.0.143:6379
  # Auth password for redis server connection.  (default: null)
  password: xwredis
  # The minimum number of idle connections to maintain in the pool.  (default: 0)
  minIdle: 0
  # The maximum number of idle connections allowed in the pool.  (default: 0)
  maxIdle: 0
  # The maximum number of connections allowed in the pool.  (default: 1024)
  maxTotal: 1924
  # Enables SSL connection. (default: false)
  ssl: false
  # The configured timeout (in milliseconds) for redis connections in the connection pool.  (default: 2000)
  timeout: 2000

# Avoid using the default 8080 port for RESTFul services
server:
   applicationConnectors:
     - type: http
       port: 8081
   adminConnectors:
     - type: http
       port: 8082

# Logging For the record
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO,
  # DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console
      timeZone: GMT+08:00
    - type: file
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: logfile.log
      archivedLogFilenamePattern: logfile-%d.log.gz
      archivedFileCount: 5
      timeZone: GMT+08:00
    - type: gelf
      host: udp:172.16.0.143
      extractStackTrace: true
      filterStackTrace: true
      includeFullMDC: true
      additionalFields:
         data_center: DC01
         rack: R5C2
         inception_year: 2016
      additionalFieldTypes:
         inception_year: long
         request_id: long
